/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 14 18:46:39 GMT 2017
 */

package dominion;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dominion.Cards;
import dominion.Deck;
import dominion.PlayDominion;
import dominion.Player;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Deck_ESTest extends Deck_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Deck.getMoneyDeck();
      Deck.getActionDeck();
      Deck.getVCDeck();
      PlayDominion.Players = null;
      // Undeclared exception!
      try { 
        Deck.Build_Money_Victory();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("dominion.Deck", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Deck.Build_Action_Deck();
      LinkedList<Player> linkedList0 = new LinkedList<Player>();
      linkedList0.add((Player) null);
      linkedList0.add((Player) null);
      linkedList0.offerLast((Player) null);
      linkedList0.add((Player) null);
      PlayDominion.Players = (List<Player>) linkedList0;
      Deck.Build_Money_Victory();
      Deck.Build_Money_Victory();
      Deck deck0 = new Deck();
      Deck deck1 = new Deck();
      Deck.getActionDeck();
      Deck.Build_Action_Deck();
      List<Cards> list0 = Deck.curseCards;
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Deck.getVCDeck();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Deck.Build_Money_Victory();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Deck.Build_Action_Deck();
      Deck.Build_Money_Victory();
      LinkedList<Player> linkedList0 = new LinkedList<Player>();
      linkedList0.add((Player) null);
      linkedList0.add((Player) null);
      linkedList0.pollFirst();
      linkedList0.add(0, (Player) null);
      linkedList0.addFirst((Player) null);
      PlayDominion.Players = (List<Player>) linkedList0;
      Deck deck0 = new Deck();
      Deck.getActionDeck();
      Deck.getActionDeck();
      Deck.Build_Money_Victory();
      Deck.getActionDeck();
      List<Cards> list0 = Deck.curseCards;
      Deck deck1 = new Deck();
      Deck.getActionDeck();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      List<List<Cards>> list0 = (List<List<Cards>>)Deck.getMoneyDeck();
      assertEquals(0, list0.size());
      
      Deck.Build_Action_Deck();
      Deck.Build_Action_Deck();
      Deck.Build_Money_Victory();
      LinkedList<Player> linkedList0 = new LinkedList<Player>();
      linkedList0.add((Player) null);
      linkedList0.add((Player) null);
      PlayDominion.Players = (List<Player>) linkedList0;
      Deck deck0 = new Deck();
      Deck.getActionDeck();
      Deck.getActionDeck();
      Deck.Build_Money_Victory();
      Deck.getActionDeck();
      Deck.getMoneyDeck();
      List<Cards> list1 = Deck.curseCards;
      Deck.Build_Action_Deck();
      Deck deck1 = new Deck();
      List<List<Cards>> list2 = (List<List<Cards>>)Deck.getActionDeck();
      assertEquals(30, list2.size());
  }
}
