version: '3.6'
services:
  database:
     image: postgres
     restart: always
     environment:
        POSTGRES_PASSWORD: ${PGPASSWORD}
        POSTGRES_USER: ${PGUSER}
        POSTGRES_DB: ${PGDATABASE}
     ports:
       - "32769:5432"
     volumes:
        - ./db-init:/docker-entrypoint-initdb.d
        - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: brewhops-postgress-data
